# pull official base image
FROM python:3.8-slim-buster

# set working directory
WORKDIR /usr/src/app

# install python dependencies
RUN python -m pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN python -m spacy download en_core_web_sm

# add app
COPY . .

#run on heroku
CMD uvicorn app.main:app --workers 1 --host 0.0.0.0 --port $PORT